version: '3.8'

services:
  ss_mariadb:
    image: linuxserver/mariadb:latest
    container_name: ss_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: TheStr34ms33dp@ssw0rd#20060925
      MYSQL_DATABASE: streamseed
      MYSQL_USER: sramsay
      MYSQL_PASSWORD: Mystreamseedpassw0rd
      PUID: 1000
      PGID: 1000
    volumes:
      - ./mariadb_data:/config
    ports:
      - "3306:3306"
    networks:
      - backend

  ss_portainer:
    image: portainer/portainer-ce:latest
    container_name: ss_portainer
    restart: always
    ports:
      - "9339:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      - frontend

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    environment:
      DATABASE_URL: "mysql+pymysql://sramsay:Mystreamseedpassw0rd@ss_mariadb/streamseed"
      PUID: 1000
      PGID: 1000
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - ss_mariadb
    networks:
      - backend

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx-container
  #   ports:
  #     - 83:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf  # Your nginx configuration file
  #     - ./web_server:/usr/share/nginx/html  # PHP application files
  #   depends_on:
  #     - php-fpm
  #   networks:
  #     - backend

  # php-fpm:
  #   image: php:7.4-fpm
  #   container_name: php-fpm-container
  #   volumes:
  #     - ./web_server:/usr/share/nginx/html  # Same volume as Nginx to share PHP files
  #   networks:
  #     - backend

  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    restart: always
    environment:
      DB_MYSQL_HOST: ss_mariadb
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: nginx
      DB_MYSQL_PASSWORD: Mutdrule01!
      DB_MYSQL_NAME: nginx
    volumes:
      - ./nginx_proxy_manager_data:/data
      - ./nginx_proxy_manager_letsencrypt:/etc/letsencrypt
    ports:
      - "84:80"     # For HTTP access
      - "444:443"   # For HTTPS access
      - "88:81"     # For Nginx Proxy Manager UI
    depends_on:
      - ss_mariadb
    networks:
      - backend

volumes:
  mariadb_data:
  portainer_data:
  nginx_proxy_manager_data:
  nginx_proxy_manager_letsencrypt:

networks:
  backend:
  frontend:
